# https://medium.com/analytics-vidhya/super-performance-stocks-how-to-make-more-than-1-125-on-a-single-small-cap-stock-with-python-5ea3ae393791
name: Super stock scanner
# Don't want to burn my private minutes at this point
on:
  push:
    branches:
      - master
    schedule:
      cron: '30 21 7 * 5'

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_INVESTING_WEBHOOK }}

jobs:
  make_report:
    name: Generate Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.6

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Generate Stock List
        run: python3 -m stock_screener.market_scanner --f cfg/super_performance.json
