name: Penny stock scanner
# Don't want to burn my private minutes at this point
on:
  push:
    branches:
      - master
    schedule:
      cron: '30 21 7 * 5'

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_INVESTING_WEBHOOK }}

jobs:
  make_report:
    name: Generate Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install dependencies
        run: poetry install

      - name: Generate Stock List
        run: poetry run python -m stock_screener.market_scanner --f cfg/penny_stocks.json
