name: Penny stock scanner
# Don't want to burn my private minutes at this point
on:
  push:
    branches:
      - master
    schedule:
      cron: '30 21 7 * 5'

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_INVESTING_WEBHOOK }}

jobs:
  make_report:
    name: Generate Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9
          args: install

      - name: Generate Stock List
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.7
          poetry_version: 1.0.9
          # working_directory: ./working_dir
          args: run python -m stock_screener.market_scanner --f cfg/penny_stocks.json
